config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "pools#index"
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  get "/mybookings", to: "pages#mybookings"

  resources :users, only: [:show]
  resources :pools, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :saved_pools, only: [:create, :destroy]
  end
  patch '/bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  patch '/bookings/:id/decline', to: 'bookings#decline', as: :decline_booking
  patch '/bookings/:id/cancel', to: 'bookings#cancel', as: :cancel_booking

  resources :saved_pools, only: [:index]
  resources :bookings, only: [:show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pool
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: { greater_than: :start_date }
  validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validate :no_overlapping_bookings

  STATUS = %w[pending accepted declined canceled]
  
  private

  def no_overlapping_bookings
    if pool && start_date && end_date
      overlapping_bookings = pool.bookings.where.not(id: id).where("start_date < ? AND end_date > ?", end_date, start_date)
      if overlapping_bookings.exists?
        errors.add(:base, "This booking overlaps with another booking for the same pool")
      end
    end
  end
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :saved_pools, dependent: :destroy
  has_many :saved_by_users, through: :saved_pools, source: :user
  # ligne suivante à decommenter si nécessaire
  # has_many :users, through: :bookings

  # on lie une photo Active Storage (ajout Remi)
  has_one_attached :photo
  # Validations
  validates :address, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :price_per_day, presence: true, numericality: { greater_than: 0 }
  validates :overview, length: { maximum: 1500 }
  # Geocoding
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_overview,
    against: [:name, :overview],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/saved_pool.rb
class SavedPool < ApplicationRecord
  belongs_to :user
  belongs_to :pool
  validates :user_id, uniqueness: { scope: :pool_id, message: "has already saved this pool" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pools
  has_many :bookings
  has_many :saved_pools, dependent: :destroy

  # On peut définir des has-many custom pour faire des raccourcis
  has_many :booking_requests, through: :pools, source: :bookings

  validates :pseudo, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :first_name_and_last_name_must_be_different_from_pseudo
  has_one_attached :photo

  private

  def first_name_and_last_name_must_be_different_from_pseudo
    puts first_name.downcase
    puts pseudo.downcase
    if first_name.downcase == pseudo.downcase
      errors.add(:first_name, "must be different from your pseudo")
    elsif last_name.downcase == pseudo.downcase
      errors.add(:last_name, "must be different from your pseudo")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :pseudo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :pseudo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @pool = Pool.find(params[:pool_id])
    @booking = Booking.new(booking_params)
    @booking.pool = @pool
    @booking.user = current_user
    @booking.status = "pending"
    @booking.total_price = (@booking.end_date.day - @booking.start_date.day) * @booking.pool.price_per_day
    if @booking.save
      redirect_to booking_path(@booking), notice: "Your booking has been created"
    else
      render "pools/show", status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = 'confirmed'
    @booking.save
    redirect_to dashboard_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = 'declined'
    @booking.save
    redirect_to dashboard_path
  end

  def cancel
    @booking = Booking.find(params[:id])
    @booking.status = 'cancelled'
    @booking.save
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @user = current_user
    @booking_requests = Booking.where(pool: @user)
  end

  def mybookings
    @bookings = current_user.bookings
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  # skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :index
  before_action :set_pool, only: [:show]

  def index
    if params[:query].present?
      @pools = Pool.search_by_name_and_overview(params[:query])
    else
      @pools = Pool.all
    end
    @markers = @pools.geocoded.map do |pool|
      {
        lat: pool.latitude,
        lng: pool.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { pool: pool }),
        marker_html: render_to_string(partial: "map_marker", locals: { pool: pool })
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @pool = Pool.new
  end

  def create
    @pool = Pool.new(pool_params)
    @pool.user = current_user
    if @pool.save
      redirect_to saved_pools(@pool)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_pool
    @pool = Pool.find(params[:id])
  end

  def pool_params
    params.require(:pool).permit(:name, :address, :area, :pool_type, :price_per_day, :photo)
  end
end

app/controllers/saved_pools_controller.rb
class SavedPoolsController < ApplicationController
  before_action :authenticate_user!

  def index
    @saved_pools = current_user.saved_pools
  end

  def create
    @pool = Pool.find(params[:pool_id])
    @saved_pool = current_user.saved_pools.build(pool: @pool)

    if @saved_pool.save
      redirect_to saved_pools_path, anchor: @pool.id, notice: "Piscine sauvegardée avec succès."
    else
      redirect_to pools_path, alert: "Impossible de sauvegarder la piscine."
    end
  end

  def destroy
    @pool = Pool.find(params[:pool_id])
    @saved_pool = current_user.saved_pools.find_by(pool: @pool)
    if @saved_pool.destroy
      redirect_to request.referrer, aler: "Piscine enlevée avec succès"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    # @booking = Booking.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4 mb-5 px-2">
  <div class="text-center">
    <h1>MY BOOKING</h1>
    <hr>
    <h2 class="mb-3">LAST ONE BOOKED</h2>
  </div>

    <div class="text-center">
      <% if @booking.nil? %>
        <p>No bookings found.</p>
      <% else %>
        <div class="booking-detail m-auto">
          <h3 class="mb-4"><%= @booking.pool.name %></h3>

          <%= link_to booking_path(@booking) do %>
            <% if @booking.pool.photo.attached? %>
              <%= cl_image_tag @booking.pool.photo.key, class: 'img-fluid mx-auto my-3 rounded-5', width: '600', height: '400', crop: :fill %>
            <% else %>
              <%= image_tag 'placeholder-image.jpg', class: 'img-fluid mx-auto my-3 rounded-5', alt: "Pool picture", width: '600', height: '400' %>
            <% end %>
          <% end %>

          <div class="row mt-4">
            <div class="col">
              <strong>Arrival:</strong>
              <p><%= @booking.start_date.strftime('%B %d, %Y') %></p>
            </div>
            <div class="col">
              <strong>Departure:</strong>
              <p><%= @booking.end_date.strftime('%B %d, %Y') %></p>
            </div>
          </div>

          <div class="my-4">
            <h4>My Host</h4>
            <div class="media">
              <% if @booking.pool.user.photo.attached? %>
                <%= cl_image_tag @booking.pool.user.photo.key, transformation: { width: 50, height: 50, crop: "thumb", gravity: "face" }, class: "mr-3 rounded-circle", alt: "Host Image" %>
              <% else %>
                <%= image_tag 'placeholder-user.png', class: "mr-3 rounded-circle", alt: "Host Image", width: 50, height: 50 %>
              <% end %>
              <div class="media-body">
                <h5 class="mt-1"><%= "#{@booking.pool.user.first_name} #{@booking.pool.user.last_name}" %></h5>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div class="mt-4 mb-2 d-flex justify-content-start">
        <h4>Details</h4>
        <hr>
      </div>
      <div class="my-2 d-flex justify-content-start">
        <ul style="list-style-type: none; padding-inline-start: 0;">
          <li><strong>Status:</strong> <%= @booking.status %></li>
          <li><strong>Address:</strong> <%= @booking.pool.address %></li>
          <li><strong>Total Price:</strong> €<%= @booking.total_price %></li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splashspace</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%# <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css"> %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<%= render 'shared/navbar' %>

<div class="container-fluid text-center mt-3">
  <h1>MY ACCOUNT</h1>
  <hr>
  <h2>BOOKING REQUESTS</h2>
  <div class="d-flex flex-wrap">
    <% @user.booking_requests.each do |booking| %>
    <%# la classe booking de la div ci-dessous n'est pas encore définie en CSS %>
    <%# lien à mettre à jour avec la bonne route %>
      <div class="booking-card m-auto">
        <%= link_to '#', class:"text-decoration-none" do %>
          <h3><%= booking.pool.name %></h3>
          <% if booking.pool.photo.attached? %>
            <%= cl_image_tag booking.pool.photo.key, class:'img-fluid mx-auto my-3 rounded-5', width: '500', crop: :fill %>
          <% else %>
            <%= image_tag 'placeholder-image.jpg', class:'img-fluid mx-auto my-3 rounded-5', alt: "Pool picture", width: '500' %>
          <% end %>
          <ul style="list-style-type: none;padding-inline-start:0px;">
            <li>Status: <%= booking.status %></li>
            <li>Price: €<%= booking.total_price %></li>
            <li>Starts: <%= booking.start_date.strftime("%d/%m/%Y") %></li>
            <li>Ends: <%= booking.end_date.strftime("%d/%m/%Y") %></li>
            <li>User: <%= booking.user.pseudo %></li>
          </ul>
        <% end %>
        <% if booking.status == 'pending' %>
          <div class="d-flex justify-content-evenly">
            <%= link_to accept_booking_path(booking), data: { turbo_method: :patch } do %>
              <div class="btn btn-outline-primary"><i class="fa-solid fa-check"></i> Accept</div>
            <% end %>
            <%= link_to decline_booking_path(booking), data: { turbo_method: :patch } do %>
              <div class="btn btn-outline-danger"><i class="fa-solid fa-xmark"></i> Decline</div>
            <% end %>
          </div>
        <% elsif booking.status == 'confirmed' %>
            <%= link_to cancel_booking_path(booking), data: { turbo_method: :patch } do %>
              <div class="btn btn-outline-danger m-auto"><i class="fa-solid fa-xmark"></i> Cancel</div>
            <% end %>
        <% end %>
        <hr>
      </div>
    <% end %>
  </div>

  <div>
    <h2 style='display:inline;'>MY POOLS</h2>
    <%= link_to new_pool_path do %>
      <h2 style='display:inline;color:black;'><i class="fa-solid fa-plus"></i></h2>
    <% end %>
  </div>
  <div class="d-flex flex-wrap">
    <% @user.pools.each do |pool| %>
      <div class="m-auto">
        <%= link_to pool_path(pool) do %>
          <%# Si une photo de pool existe on l'affiche sinon on affiche le placeholder%>
          <%# Il faudrait refacto en utilisant la partial pool_card %>
          <% if pool.photo.attached? %>
            <%= cl_image_tag pool.photo.key, class:'img-fluid mx-auto my-3 rounded-5', width: '500', crop: :fill %>
          <% else %>
            <%= image_tag 'placeholder-image.jpg', class:'img-fluid mx-auto my-3 rounded-5', alt: "Pool picture", width: '500' %>
          <% end %>
        <% end %>

          <h3><%= pool.name.upcase %></h2>
          <p>Location: <%= pool.address %></p>
          <p>Rating: ★★★★☆</p>
          <p>Price: €<%= pool.price_per_day %> per person per day</p>
          <hr>
        </div>
    <% end %>
  </div>
  <h2>PROFILE</h2>
  <ul style="list-style-type: none;padding-inline-start:0px;padding-bottom:60px;">
    <li>Pseudo: <%= @user.pseudo %></li>
    <li>First name: <%= @user.first_name %></li>
    <li>Last name: <%= @user.last_name %></li>
    <li>Email: <%= @user.email %></li>
    <li>Joined: <%= @user.created_at.strftime("%d/%m/%Y") %></li>
  </ul>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/mybookings.html.erb
<%= render 'shared/navbar' %>

<div class="container-fluid text-center mt-3 mb-5">
  <h2>MY BOOKINGS</h2>
  <div class="d-flex flex-wrap">
    <% @bookings.each do |booking| %>
    <%# la classe booking de la div ci-dessous n'est pas encore définie en CSS %>
    <%# lien à mettre à jour avec la bonne route %>
      <div class="booking-card m-auto">
        <%= link_to "#", class:"text-decoration-none" do %>
          <h3><%= booking.pool.name %></h3>
          <% if booking.pool.photo.attached? %>
            <%= cl_image_tag booking.pool.photo.key, class:'img-fluid mx-auto my-3 rounded-5', width: '500', crop: :fill %>
          <% else %>
            <%= image_tag 'placeholder-image.jpg', class:'img-fluid mx-auto my-3 rounded-5', alt: "Pool picture", width: '500' %>
          <% end %>
          <ul style="list-style-type: none;padding-inline-start:0px;">
            <li>Status: <%= booking.status %></li>
            <li>Price: €<%= booking.total_price %></li>
            <li>Starts: <%= booking.start_date.strftime("%d/%m/%Y") %></li>
            <li>Ends: <%= booking.end_date.strftime("%d/%m/%Y") %></li>
          </ul>
          <hr>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pools/_booking_form.html.erb
<%= simple_form_for [pool, booking], html: { data: { controller: "flatpickr" } } do |f| %>
  <div>
    <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: 'startDateInput' } }, label: false, placeholder: "Start date..."%>
    <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: 'endDateInput' } }, label: false, placeholder: "End date..."%>
    <p class='mb-0'>Total price =</p>
  </div>
  <div class="d-flex justify-content-center">
    <%= f.button :submit, class:"gray-rounded-btn" %>
  </div>
<% end %>

app/views/pools/_info_window.html.erb
<%= link_to pool_path(pool) do %>
  <%# Pool photo %>
  <div class="pool-thumbnail-container">
    <% if pool.photo.attached? %>
      <%= cl_image_tag pool.photo.key, class:'img-fluid mx-auto mb-1', width: '500', crop: :fill %>
    <% else %>
      <%= image_tag 'placeholder-image.jpg', class:'img-fluid mx-auto mb-1', alt: "Pool picture", width: '500' %>
    <% end %>
  </div>
  <%# /pool photo %>
  <div class="map-info-window-text">
    <h6><%= pool.name %></h6>
    <p><strong>€ <%= pool.price_per_day %> </strong> per day</p>
  </div>
<% end %>

app/views/pools/_map_marker.html.erb
<div class="map-marker">
  € <%= pool.price_per_day.round %>
</div>

app/views/pools/_new_pool_form.html.erb
<%= simple_form_for pool do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :pool_type %>
  <%= f.input :area, hint: 'In m²' %>
  <%= f.input :price_per_day, hint: 'In €' %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn-outline-secondary' %>
<% end %>

app/views/pools/new.html.erb
<%= render 'shared/navbar' %>

<div class="container-fluid mt-3">
  <div class="d-flex justify-content-between mb-3">
    <h2 class="flex-start">NEW POOL</h2>
    <%= link_to request.referer do %>
      <i class="fa-solid fa-xmark flex-end close-x-mark me-3"></i>
    <% end %>
  </div>
  <%= render 'new_pool_form', pool: @pool %>
</div>

app/views/pools/show.html.erb
<%= render 'shared/navbar' %>

<div class="container-fluid">
  <div class="d-flex justify-content-center">
    <% if @pool.photo.attached? %>
      <%= cl_image_tag @pool.photo.key, class:'img-fluid mx-auto my-3 rounded-5', width: '500', crop: :fill %>
    <% else %>
      <%= image_tag 'placeholder-image.jpg', class:'img-fluid mx-auto my-3 rounded-5', alt: "Pool picture", width: '500' %>
    <% end %>
  </div>

  <h2 class="secondary-title text-center"><%= @pool.name.upcase %></h2>
    <div class="d-flex justify-content-center">
      <% if current_user.saved_pools.exists?(pool: @pool) %>
        <%= link_to 'Unsave', pool_saved_pool_path(@pool, current_user.saved_pools.find_by(pool_id: @pool.id)), data: { turbo_method: :delete }, class: "gray-large-rounded-btn-hover-red" %>
      <% else %>
        <%= link_to 'Save', pool_saved_pools_path(@pool), data: { turbo_method: :post }, class: "gray-large-rounded-btn-hover-green" %>
      <% end %>
    </div>
  <hr>
  <p>Location: <%= @pool.address %></p>
  <p>Rating: ★★★★☆</p>
  <p>Price: €<%= @pool.price_per_day %> per person per day</p>
  <h2 class="secondary-title mt-3">DESCRIPTION</h2>
  <hr>
  <p><%= @pool.overview %></p>

  <%# On affiche la possibilité de réserver et le nom du user que si ce n'est pas le proprio %>
  <% if @pool.user != current_user %>
  <div class="container-fluid border p-3 mb-2">
    <div class="booking-card">
    <%# Formulaire non mis en forme, methode bookings#create non définie %>
    <%= render 'pools/booking_form', pool: @pool, booking: @booking %>
    </div>
  </div>



  <h2 class="secondary-title text-center">YOUR HOST</h2>
  <p class="text-center">Hosted by <%= @pool.user.first_name %></p>

  <%# Si une photo de user existe on l'affiche sinon on affiche le placeholder%>
  <div class="avatar-square mx-auto my-3">
    <% if @pool.user.photo.attached? %>
        <%= cl_image_tag @pool.user.photo.key, class:'img', size: '164', crop: :fill %>
      <% else %>
        <%= image_tag 'placeholder-image.jpg', class:'img', alt: "Pool picture" %>
      <% end %>
  </div>
  <% end %>

</div>

<%= render 'shared/footer' %>

app/views/saved_pools/index.html.erb
  <%= render 'shared/navbar' %>
<!-- j'appelle la partial navbar-->
<h1 class="text-centered">My Saved Pools</h1>
  <hr>

<div>
  <div class="fav-list d-flex flex-wrap">
    <% @saved_pools.each do |saved_pool| %>
      <%= render 'saved_pools/partials/saved_pool_card', pool: saved_pool.pool %>
      <!-- j'appelle la partial saved_poil_card-->
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>
<!-- j'appelle la partial footer-->

app/views/saved_pools/partials/_saved_pool_card.html.erb
<div class="saved-pool-card">
  <%= link_to pool_path(pool), class: "text-decoration-none" do %>
    <% if pool.photo.attached? %>
      <%= cl_image_tag pool.photo.key, class: 'img-fluid mx-auto', width: '500', crop: :fill %>
    <% else %>
      <%= image_tag 'placeholder-image.jpg', class: 'img-fluid mx-auto', alt: 'Pool picture', width: '500' %>
    <% end %>
    <div class="pool-details">
      <div class="d-flex justify-content-center">
        <h3><%= pool.name %></h3>
      </div>
      <div class="d-flex justify-content-center">
        <% if current_user.saved_pools.exists?(pool: pool) %>
        <%= link_to 'Unsave', pool_saved_pool_path(pool, current_user.saved_pools.find_by(pool_id: pool.id)), data: { turbo_method: :delete }, class: "gray-rounded-btn-hover-red" %>
        <% else %>
        <%= link_to 'Save', pool_saved_pools_path(pool), data: { turbo_method: :post }, class: "gray-rounded-btn-hover-green" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top" data-controller="navbar-scroll-downl" data-navbar-scroll-downl-target="navbar" data-action="scroll@window->navbar-scroll-downl#handleScroll">
  <div class="navbar__left">
    <%= link_to :back, class: "icon-link back-button" do %>
      <i class="fa-solid fa-angle-left"></i>
    <% end %>
  </div>

  <div class="navbar__center">
  </div>

  <div class="navbar__right">
  <%# le bouton logout ne s'affiche que dans le dashboard %>
    <% if params[:controller] == 'pages' && params[:action] == 'dashboard' %>
        <%= link_to destroy_user_session_path, data: { "turbo-method": :delete }, class:'text-decoration-none' do %>
          <div class="black-rounded-btn d-flex">Log Out</div>
        <% end %>
    <% end %>
  <%# Les sliders ne s'affichent que sur la page d'accueil %>
  <% if params[:controller] == 'pools' && params[:action] == 'index' %>
    <%= link_to root_path, class: "icon-link" do %>
      <i class="fas fa-sliders-h"></i>
    <% end %>
  <% end %>
  </div>

  <% if params[:controller] == 'pools' && params[:action] == 'index' %>
    <div class="search-bar" data-navbar-scroll-downl-target="searchBar" >
      <%= form_with url: pools_path, method: :get, local: true, class: "search-form", data:{ navbar_scroll_downl_target:"formSearchBar" } do %>
        <%= text_field_tag :query, params[:query], placeholder: "Search pools...", class: "search-input" %>
        <%= submit_tag "Search", class: "search-button" %>
      <% end %>
    </div>
  <% end %>

</nav>

<nav class="navbar-bottom">
  <ul class="nav-list">
    <li class="nav-item">
      <%= link_to root_path, class: "nav-link" do %>
        <i class="fas fa-search <%= 'active' if params[:controller] == 'pools' && params[:action] == 'index' %>"></i>
        <span class="<%= 'active' if params[:controller] == 'pools' && params[:action] == 'index' %>">Explorer</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to saved_pools_path, class: "nav-link" do %>
        <i class="fas fa-heart"></i>
        <span>Favorites</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to mybookings_path, class: "nav-link" do %>
          <%= image_tag("icon-logo.png", class:"nav-link logo")%>
          <span>bookings</span>
      <% end %>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link">
        <i class="fas fa-comment"></i>
        <span>Messages</span>
      </a>
    </li>
    <li class="nav-item">
      <div class="nav-link">
        <% if user_signed_in? && current_user.photo.attached? %>
          <%= link_to dashboard_path, class: "profile-link" do %>
            <%= cl_image_tag current_user.photo.key, class: "avatar-rounded mb-1" %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "profile-link" do %>
            <%= image_tag("default-profile-picture.png", class: "avatar-rounded mb-1") %>
          <% end %>
        <% end %>
          <span class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'dashboard' %>">
            <% if user_signed_in?%>
              Profile
            <% else %>
              Connexion
            <% end %>
          </span>
      </div>
    </li>
  </ul>
</nav>

app/views/shared/_pool-card.html.erb
<div class="pool-card" id="<%= pool.id %>">
  <%= link_to pool_path(pool), class:"text-decoration-none" do %>
    <% if pool.photo.attached? %>
      <%= cl_image_tag pool.photo.key, class:'img-fluid mx-auto', width: '500', crop: :fill %>
    <% else %>
      <%= image_tag 'placeholder-image.jpg', class:'img-fluid mx-auto', alt: "Pool picture", width: '500' %>
    <% end %>
    <div class="pool-details">
      <h3><%= pool.name %></h3>
      <p><%= pool.overview %></p>
      <div class="d-flex justify-content-between">
        <p class="price"><%= pool.price_per_day %>€ per day</p>
        <div>
          <% if current_user&.saved_pools&.exists?(pool: pool) %>
            <%= link_to 'Unsave',  pool_saved_pool_path(pool, current_user.saved_pools.find_by(pool_id: pool.id)), data: { turbo_method: :delete }, class: "gray-rounded-btn-hover-red" %>
          <% else %>
            <%= link_to 'Save', pool_saved_pools_path(pool), data: { turbo_method: :post}, class: "gray-rounded-btn-hover-green" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>Page déplacée dans pages#dashboard, path: dashboard_path</h2>